permalink: /:year/:month/:day/:title.html
highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      entity: Keystone Ledger Lens
      site_author: Keystone Ledger Lens
      site_description: Keystone Ledger Lens
      title: Keystone Ledger Lens
      subtitle: Revealing Budgetary Magic Tricks
      quip: Fact-checking Pennsylvania's multi-billion-dollar creative writing project.
      logo_url: https://avatars.githubusercontent.com/u/297656775
      style_css: /www/css/www.css
      site_js: /www/js/dashboard.js
      branding_ico: /www/img/branding/brand.ico
